name: ci

on: 
  workflow_dispatch:
    inputs:
      id:
        description: Run ID.
        required: false
      workflow_inputs:
        description: The JSON-encoded workflow inputs.
        required: false

jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}

  # Based on: https://github.community/t/how-to-feed-workflow-dispatch-inputs-into-a-test-matrix/247548/2
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          workflow_inputs=${{github.event.inputs.workflow_inputs}}
          os=echo ${workflow_inputs} | jq -r '.os'
          if [ -z ${os} ]; then
            echo "::set-output name=os::['ubuntu-18.04', 'ubuntu-20.04']"
          else
            echo "::set-output name=os::['${os}']"
          fi
    outputs:
      os: ${{ steps.set-matrix.outputs.os }}

  validation:
    name: Validation
    needs: setup
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.os) }}
        version: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: greetings
        run: echo ${{ matrix.os }}
